name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-stable:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Extract major version
        run: echo "MAJOR_VERSION=v${GITHUB_REF#refs/tags/v}" | cut -d '.' -f 1 >> $GITHUB_ENV
      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y g++ make pkg-config libgtk-3-dev libcanberra-gtk-module libcanberra-gtk3-module libgl-dev libasound2-dev libao-dev libopenal-dev libsdl2-dev libsdl2-2.0-0 git wget file gpg appstream libfuse2t64 pkgconf

      - name: Build ares
        run: |
          git clone -b $MAJOR_VERSION https://github.com/ares-emulator/ares
          cd ares
          mkdir -p AppDir/usr
          make clean
          make -j$(nproc) install build=release hiro=gtk3 local=false platform=linux prefix=../AppDir/usr

      - name: Build appimage
        run: |
          cd ares
          wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
          wget https://github.com/darealshinji/linuxdeploy-plugin-checkrt/releases/download/continuous/linuxdeploy-plugin-checkrt.sh
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/2.0.0-alpha-1-20241106/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-plugin-gtk.sh linuxdeploy-plugin-checkrt.sh linuxdeploy-x86_64.AppImage
          export LINUXDEPLOY_OUTPUT_VERSION="${MAJOR_VERSION}"
          export LD_LIBRARY_PATH=AppDir/usr/lib
          mkdir -p AppDir/usr/share/metainfo
          cp ../net.ares.emu.appdata.xml AppDir/usr/share/metainfo/
          cp desktop-ui/resource/ares.desktop desktop-ui/resource/net.ares.emu.desktop
          mkdir -p AppDir/usr/lib
          cp /usr/lib/x86_64-linux-gnu/{libcanberra.so.0,libcanberra-gtk3.so.0,libGL.so.1,libGL.so.1.7.0} AppDir/usr/lib
          ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir AppDir --plugin gtk --plugin checkrt --output appimage --desktop-file desktop-ui/resource/net.ares.emu.desktop --icon-file desktop-ui/resource/ares.png

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          files: /home/runner/work/ares-emu-appimage/ares-emu-appimage/ares/ares*.AppImage*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
