name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-stable:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Extract major version
        run: echo "MAJOR_VERSION=v${GITHUB_REF#refs/tags/v}" | cut -d '.' -f 1 >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential cmake pkg-config curl git clang ninja-build ccache
          sudo apt-get install -y libgtk-3-dev libcanberra-gtk-module libgl-dev libasound2-dev libao-dev libopenal-dev libsdl2-dev libpulse-dev libudev-dev
          sudo apt-get install -y wget file gpg appstream pkgconf

      - name: Install librashader
        run: |
          mkdir librashader && cd librashader
          wget http://download.opensuse.org/repositories/home:/chyyran:/librashader/Debian_12/amd64/librashader_1735190467.984fd6f-57.3_amd64.deb
          sudo apt-get install -y ./*.deb

      - name: Build ares
        run: |
          git clone -b v143 https://github.com/ares-emulator/ares
          cd ares
          mkdir -p AppDir/usr
          mkdir build && cd build
          cmake .. -G Ninja
          cmake --build . -j$(nproc)
          cmake --install . --strip --prefix ../AppDir/usr

      - name: Build appimage
        run: |
          export OUTPUT="ares-v${{ github.ref_name }}-x86_64.AppImage"
          export LINUXDEPLOY_OUTPUT_VERSION="${MAJOR_VERSION}"
          export APPIMAGE_EXTRACT_AND_RUN=1
          export LD_LIBRARY_PATH=AppDir/usr/lib
          export DEPLOY_GTK_VERSION=3
          cd ares
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20250213-2/linuxdeploy-x86_64.AppImage
          wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-plugin-gtk.sh linuxdeploy-x86_64.AppImage
          mkdir -p AppDir/usr/share/metainfo
          cp ../net.ares.emu.appdata.xml AppDir/usr/share/metainfo/
          cp desktop-ui/resource/ares.desktop desktop-ui/resource/net.ares.emu.desktop
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin gtk --output appimage --desktop-file desktop-ui/resource/net.ares.emu.desktop --icon-file desktop-ui/resource/ares.png --library /usr/lib/x86_64-linux-gnu/librashader.so

      - name: Upload AppImage as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ares_AppImage
          path: /home/runner/work/ares-emu-appimage/ares-emu-appimage/ares/ares*.AppImage*
